# 服务端口
server:
  port: 8001
  # 服务名

spring:
  application:
    name: edu-eduservice
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.150.131:3306/xxjx_edu?serverTimezone=GMT%2B8
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 热部署配置
  devtools:
    restart:
      enabled: true

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 自定义配置阿里云OSS
aLiYun:
  oss:
    file:
      endPoint: oss-cn-beijing.aliyuncs.com
      keyId: LTAI4FoHRan3mQnF74xZ15PB
      keySecret: NngMvehcffkz8AI3LV0RnlD5mPZG3A
      # bucket可以在控制台创建，也可以使用java代码创建
      bucketName: musha
      fileHost: avatar

